"""change  student table sleep time format

Revision ID: 2a1d945bd07c
Revises: e600883d0964
Create Date: 2025-12-23 19:37:28.786476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1d945bd07c'
down_revision: Union[str, Sequence[str], None] = 'e600883d0964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'weekend_sleep_time',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    op.alter_column('students', 'weekend_wake_time',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'weekend_wake_time',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    op.alter_column('students', 'weekend_sleep_time',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###
