"""Initial student table

Revision ID: df6e5b6ab90e
Revises: 
Create Date: 2025-12-23 15:25:56.842847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6e5b6ab90e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('is_smoker', sa.Boolean(), nullable=False),
    sa.Column('weekday_sleep_time', sa.Time(), nullable=False),
    sa.Column('weekday_wake_time', sa.Time(), nullable=False),
    sa.Column('weekend_sleep_time', sa.Time(), nullable=False),
    sa.Column('weekend_wake_time', sa.Time(), nullable=False),
    sa.Column('goes_home_on_weekend', sa.Boolean(), nullable=False),
    sa.Column('late_night_return_frequency', sa.Integer(), nullable=False),
    sa.Column('drinking_frequency', sa.Integer(), nullable=False),
    sa.Column('noise_sensitivity', sa.Integer(), nullable=False),
    sa.Column('call_frequency', sa.Integer(), nullable=False),
    sa.Column('snores', sa.Boolean(), nullable=False),
    sa.Column('prefers_same_major', sa.Boolean(), nullable=False),
    sa.Column('major_name', sa.String(length=100), nullable=False),
    sa.Column('cleaning_frequency', sa.Integer(), nullable=False),
    sa.Column('personality_extroversion', sa.Integer(), nullable=False),
    sa.Column('weight_lifestyle_rhythm', sa.Integer(), nullable=True),
    sa.Column('weight_noise', sa.Integer(), nullable=True),
    sa.Column('weight_major', sa.Integer(), nullable=True),
    sa.Column('weight_cleaning', sa.Integer(), nullable=True),
    sa.Column('weight_age', sa.Integer(), nullable=True),
    sa.Column('weight_personality', sa.Integer(), nullable=True),
    sa.Column('is_matched', sa.Boolean(), nullable=True),
    sa.Column('matched_room_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("gender IN ('male', 'female', 'other')", name='check_gender'),
    sa.CheckConstraint('age >= 18 AND age <= 100', name='check_age_range'),
    sa.CheckConstraint('call_frequency >= 0 AND call_frequency <= 7', name='check_call_frequency_range'),
    sa.CheckConstraint('cleaning_frequency >= 0 AND cleaning_frequency <= 7', name='check_cleaning_range'),
    sa.CheckConstraint('drinking_frequency >= 0 AND drinking_frequency <= 7', name='check_drinking_range'),
    sa.CheckConstraint('late_night_return_frequency >= 0 AND late_night_return_frequency <= 7', name='check_late_night_range'),
    sa.CheckConstraint('noise_sensitivity >= 1 AND noise_sensitivity <= 5', name='check_noise_sensitivity_range'),
    sa.CheckConstraint('personality_extroversion >= 1 AND personality_extroversion <= 5', name='check_personality_range'),
    sa.CheckConstraint('weight_age >= 0 AND weight_age <= 100', name='check_weight_age'),
    sa.CheckConstraint('weight_cleaning >= 0 AND weight_cleaning <= 100', name='check_weight_cleaning'),
    sa.CheckConstraint('weight_lifestyle_rhythm >= 0 AND weight_lifestyle_rhythm <= 100', name='check_weight_lifestyle'),
    sa.CheckConstraint('weight_major >= 0 AND weight_major <= 100', name='check_weight_major'),
    sa.CheckConstraint('weight_noise >= 0 AND weight_noise <= 100', name='check_weight_noise'),
    sa.CheckConstraint('weight_personality >= 0 AND weight_personality <= 100', name='check_weight_personality'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_gender'), 'students', ['gender'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_is_matched'), 'students', ['is_matched'], unique=False)
    op.create_index(op.f('ix_students_is_smoker'), 'students', ['is_smoker'], unique=False)
    op.create_index(op.f('ix_students_major_name'), 'students', ['major_name'], unique=False)
    op.create_index(op.f('ix_students_student_id'), 'students', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_student_id'), table_name='students')
    op.drop_index(op.f('ix_students_major_name'), table_name='students')
    op.drop_index(op.f('ix_students_is_smoker'), table_name='students')
    op.drop_index(op.f('ix_students_is_matched'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_gender'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
