"""Change room_id to integer and add satisfaction scores

Revision ID: e600883d0964
Revises: e89c93a28ba6
Create Date: 2025-12-23 18:13:38.967614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e600883d0964'
down_revision: Union[str, Sequence[str], None] = 'e89c93a28ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Clear existing matched_room_id data (reset all matches)
    op.execute('UPDATE students SET matched_room_id = NULL, is_matched = FALSE')

    # Add new satisfaction score columns
    op.add_column('students', sa.Column('my_satisfaction_score', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('partner_satisfaction_score', sa.Float(), nullable=True))
    op.add_column('students', sa.Column('cluster_id', sa.Integer(), nullable=True))

    # Change matched_room_id type from UUID to Integer
    op.execute('ALTER TABLE students ALTER COLUMN matched_room_id TYPE INTEGER USING NULL')

    # Create index
    op.create_index(op.f('ix_students_matched_room_id'), 'students', ['matched_room_id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_matched_room_id'), table_name='students')
    op.alter_column('students', 'matched_room_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_column('students', 'cluster_id')
    op.drop_column('students', 'partner_satisfaction_score')
    op.drop_column('students', 'my_satisfaction_score')
    # ### end Alembic commands ###
