"""change  student table sleep time format

Revision ID: e89c93a28ba6
Revises: df6e5b6ab90e
Create Date: 2025-12-23 16:11:26.680871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e89c93a28ba6'
down_revision: Union[str, Sequence[str], None] = 'df6e5b6ab90e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'weekday_sleep_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('students', 'weekday_wake_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('students', 'weekend_sleep_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=2),
               existing_nullable=False)
    op.alter_column('students', 'weekend_wake_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'weekend_wake_time',
               existing_type=sa.String(length=2),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('students', 'weekend_sleep_time',
               existing_type=sa.String(length=2),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('students', 'weekday_wake_time',
               existing_type=sa.String(length=2),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('students', 'weekday_sleep_time',
               existing_type=sa.String(length=2),
               type_=postgresql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
